// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsAndroidEm
{
    internal sealed partial class Vsix
    {
        public const string Id = "VsAndroidEm.5dfcfa73-0d82-4b24-9c01-479eaa271e61";
        public const string Name = "VsAndroidEm";
        public const string Description = @"This extension embeds the Android emulator directly inside a tool window of the IDE.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Adolfo Marinucci";
        public const string Tags = "";
    }
}
